# Dimensiones y subespacios

##Primer DataFrame

In [ ]:
import pandas as pd

data = {
    'País': ['Ghana', 'Belize', 'Slovenia', 'Slovakia', 'Zambia', 'Zimbabwe',
             'Laos', 'Cambodia', 'Turkmenistan', 'Uzbekistan', 'Luxembourg',
             'France', 'Bolivia', 'United States', 'China'],
    'Dimensiones': [5, 5, 2, 4, 4, 6, 3, 4, 4, 3, 6, 7, 3, 7, 5],
    'Subespacio': [888, 806, 303, 857, 903, 1670, 738, 1248, 1024, 717, 1401, 1574, 694, 1241, 1217]
}

df = pd.DataFrame(data)
df

             País  Dimensiones  Subespacio
0           Ghana            5         888
1          Belize            5         806
2        Slovenia            2         303
3        Slovakia            4         857
4          Zambia            4         903
5        Zimbabwe            6        1670
6            Laos            3         738
7        Cambodia            4        1248
8    Turkmenistan            4        1024
9      Uzbekistan            3         717
10     Luxembourg            6        1401
11         France            7        1574
12        Bolivia            3         694
13  United States            7        1241
14          China            5        1217

## Segundo

In [ ]:
import pandas as pd

data = {
    'País': [
        'Ghana', 'Belize', 'Slovenia', 'Slovakia', 'Zambia', 'Zimbabwe',
        'Laos', 'Cambodia', 'Turkmenistan', 'Uzbekistan', 'Luxembourg',
        'France', 'Bolivia', 'United States', 'China', 'Mexico', 'Russia',
        'Belgium', 'Andorra', 'Spain', 'Belarus', 'Faroe Islands'
    ],
    'Dimensiones': [
        5, 5, 2, 4, 4, 6, 3, 4, 4, 3, 6, 7, 3, 7, 5, 7, 6, 4, 5, 6, 5, 3
    ],
    'Subespacio': [
        888, 806, 303, 857, 903, 1670, 738, 1248, 1024, 717, 1401,
        1574, 694, 1241, 970, 2845, 1562, 883, 2128, 1277, 1033, 792
    ]
}

df = pd.DataFrame(data)
print(df)

             País  Dimensiones  Subespacio
0           Ghana            5         888
1          Belize            5         806
2        Slovenia            2         303
3        Slovakia            4         857
4          Zambia            4         903
5        Zimbabwe            6        1670
6            Laos            3         738
7        Cambodia            4        1248
8    Turkmenistan            4        1024
9      Uzbekistan            3         717
10     Luxembourg            6        1401
11         France            7        1574
12        Bolivia            3         694
13  United States            7        1241
14          China            5         970
15         Mexico            7        2845
16         Russia            6        1562
17        Belgium            4         883
18        Andorra            5        2128
19          Spain            6        1277
20        Belarus            5        1033
21  Faroe Islands            3         792

## Tercero

In [ ]:
import pandas as pd

data = {
    'País': [
        'Ghana', 'Belize', 'Slovenia', 'Slovakia', 'Zambia', 'Zimbabwe',
        'Laos', 'Cambodia', 'Turkmenistan', 'Uzbekistan', 'Luxembourg',
        'France', 'Bolivia', 'United States', 'China', 'Mexico', 'Russia',
        'Belgium', 'Andorra', 'Spain', 'Belarus', 'Faroe Islands',
        'Argentina', 'Paraguay', 'Brazil', 'Canada', 'Japan', 'Italy'
    ],
    'Dimensiones': [
        5, 5, 2, 4, 4, 6, 3, 4, 4, 3, 6, 7, 3, 7, 5, 7, 6, 4, 5, 6, 5, 3,
        4, 6, 6, 7, 8, 6
    ],
    'Subespacio': [
        888, 806, 303, 857, 903, 1670, 738, 1248, 1024, 717, 1401, 1574,
        694, 1241, 970, 2845, 1562, 883, 2128, 1277, 1033, 792,
        922, 1545, 1937, 1038, 1749, 1512
    ]
}

df = pd.DataFrame(data)
print(df)

             País  Dimensiones  Subespacio
0           Ghana            5         888
1          Belize            5         806
2        Slovenia            2         303
3        Slovakia            4         857
4          Zambia            4         903
5        Zimbabwe            6        1670
6            Laos            3         738
7        Cambodia            4        1248
8    Turkmenistan            4        1024
9      Uzbekistan            3         717
10     Luxembourg            6        1401
11         France            7        1574
12        Bolivia            3         694
13  United States            7        1241
14          China            5         970
15         Mexico            7        2845
16         Russia            6        1562
17        Belgium            4         883
18        Andorra            5        2128
19          Spain            6        1277
20        Belarus            5        1033
21  Faroe Islands            3         792
22      Argentina            4         922
23       Paraguay            6        1545
24         Brazil            6        1937
25         Canada            7        1038
26          Japan            8        1749
27          Italy            6        1512

## Cuarto y último

In [ ]:
import pandas as pd

paises = [
    "Ghana", "Belize", "Slovenia", "Slovakia", "Zambia", "Zimbabwe",
    "Laos", "Cambodia", "Yemen", "Turkmenistan", "Uzbekistan", "Luxembourg",
    "France", "Bolivia", "United States", "China", "Mexico", "Russia",
    "Belgium", "Andorra", "Spain", "Belarus", "Faroe Islands", "Argentina",
    "Paraguay", "Brazil", "Germany", "Canada", "Japan", "Italy", "Morocco",
    "India", "United Kingdom", "Singapore", "Sweden", "Norway", "Portugal",
    "Ecuador", "Peru", "Burkina Faso", "French Guiana", "Mongolia",
    "Bulgaria", "Oman"
]
Dimensions = [
        5, 5, 2, 4, 4, 6, 3, 4, 6, 4, 3, 6, 7, 3, 7, 5, 7, 6, 4, 5, 6, 5, 3,
        4, 6, 6, 6, 7, 8, 6,
        4, 8, 4, 7, 7, 5, 6, 5, 6, 3, 3, 6, 4, 3
    ]

subespacios = [768] * len(Dimensions)

data = {
    "Country": paises,
    "Dimensions": Dimensions,
    "Subspace": subespacios
}


df_dims = pd.DataFrame(data)
df_dims

           Country  Dimensions  Subspace
0            Ghana           5       768
1           Belize           5       768
2         Slovenia           2       768
3         Slovakia           4       768
4           Zambia           4       768
5         Zimbabwe           6       768
6             Laos           3       768
7         Cambodia           4       768
8            Yemen           6       768
9     Turkmenistan           4       768
10      Uzbekistan           3       768
11      Luxembourg           6       768
12          France           7       768
13         Bolivia           3       768
14   United States           7       768
15           China           5       768
16          Mexico           7       768
17          Russia           6       768
18         Belgium           4       768
19         Andorra           5       768
20           Spain           6       768
21         Belarus           5       768
22   Faroe Islands           3       768
23       Argentina           4       768
24        Paraguay           6       768
25          Brazil           6       768
26         Germany           6       768
27          Canada           7       768
28           Japan           8       768
29           Italy           6       768
30         Morocco           4       768
31           India           8       768
32  United Kingdom           4       768
33       Singapore           7       768
34          Sweden           7       768
35          Norway           5       768
36        Portugal           6       768
37         Ecuador           5       768
38            Peru           6       768
39    Burkina Faso           3       768
40   French Guiana           3       768
41        Mongolia           6       768
42        Bulgaria           4       768
43            Oman           3       768

In [ ]:
import pandas as pd
from tabulate import tabulate

# Dividir el DataFrame en dos partes
mid_index = len(df_dims) // 2
df_first_half = df_dims.iloc[:mid_index]
df_second_half = df_dims.iloc[mid_index:]

# Imprimir cada mitad con formato de tabla usando tabulate
print("Primera mitad de la tabla:")
print(tabulate(df_first_half, headers='keys', tablefmt='psql', showindex=False))

print("\nSegunda mitad de la tabla:")
print(tabulate(df_second_half, headers='keys', tablefmt='psql', showindex=False))

Primera mitad de la tabla:
+---------------+--------------+------------+
| Country       |   Dimensions |   Subspace |
|---------------+--------------+------------|
| Ghana         |            5 |        768 |
| Belize        |            5 |        768 |
| Slovenia      |            2 |        768 |
| Slovakia      |            4 |        768 |
| Zambia        |            4 |        768 |
| Zimbabwe      |            6 |        768 |
| Laos          |            3 |        768 |
| Cambodia      |            4 |        768 |
| Yemen         |            6 |        768 |
| Turkmenistan  |            4 |        768 |
| Uzbekistan    |            3 |        768 |
| Luxembourg    |            6 |        768 |
| France        |            7 |        768 |
| Bolivia       |            3 |        768 |
| United States |            7 |        768 |
| China         |            5 |        768 |
| Mexico        |            7 |        768 |
| Russia        |            6 |        768 |
| Belgium       |            4 |        768 |
| Andorra       |            5 |        768 |
| Spain         |            6 |        768 |
| Belarus       |            5 |        768 |
+---------------+--------------+------------+

Segunda mitad de la tabla:
+----------------+--------------+------------+
| Country        |   Dimensions |   Subspace |
|----------------+--------------+------------|
| Faroe Islands  |            3 |        768 |
| Argentina      |            4 |        768 |
| Paraguay       |            6 |        768 |
| Brazil         |            6 |        768 |
| Germany        |            6 |        768 |
| Canada         |            7 |        768 |
| Japan          |            8 |        768 |
| Italy          |            6 |        768 |
| Morocco        |            4 |        768 |
| India          |            8 |        768 |
| United Kingdom |            4 |        768 |
| Singapore      |            7 |        768 |
| Sweden         |            7 |        768 |
| Norway         |            5 |        768 |
| Portugal       |            6 |        768 |
| Ecuador        |            5 |        768 |
| Peru           |            6 |        768 |
| Burkina Faso   |            3 |        768 |
| French Guiana  |            3 |        768 |
| Mongolia       |            6 |        768 |
| Bulgaria       |            4 |        768 |
| Oman           |            3 |        768 |
+----------------+--------------+------------+

# Saliencia

In [ ]:
# prompt: load the data_clean.csv file

import pandas as pd

# Load the dataframe.
try:
    df = pd.read_csv('data_clean.csv')
    print("Data loaded successfully.")
except FileNotFoundError:
    print("Error: 'data_clean.csv' not found. Please upload the file.")
except pd.errors.EmptyDataError:
    print("Error: 'data_clean.csv' is empty.")
except pd.errors.ParserError:
    print("Error: Unable to parse 'data_clean.csv'. Please check the file format.")

Data loaded successfully.

In [ ]:
df

,ID,ghana.luxemburgo_s,turkmeni.uzbeki_s,francia.bolivia_s,belice.eeuu_s,china.luxem_s,laos.mejico_s,rusia.burkinaf_s,francia.belgica_s,andorra.espa√±a_s,...,libano.siria_ABBA,libano.siria_rt_ABBA,brasil.portugal_ABBA,brasil.portugal.1_ABBA,portugal.uruguay_ABBA,coreasur.coreanorte_ABBA,coreanorte.venezuela_ABBA,emirarab.coreanorte_ABBA,coreanorte.yemen_ABBA,brasil.portugal_rt.1_ABBA
0,218713,a,d,d,a,d,a,d,d,a,...,7,3877.2,8,8,5,1,9,3,5,3823.7
1,2319690,a,d,a,a,d,a,d,d,a,...,5,2103.6,4,3,2,1,3,7,6,2718.3
2,2336337,a,d,d,a,d,a,d,d,a,...,7,3437.0,8,7,2,5,1,3,4,4697.3
3,2419139,a,d,d,a,d,a,d,a,a,...,7,4519.3,8,9,2,3,4,6,3,10182.2
4,2563975,a,d,d,a,d,a,d,d,a,...,5,1911.3,9,9,2,2,2,3,1,3063.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,9125906,a,a,d,a,d,a,d,d,d,...,4,3842.8,3,6,6,6,3,7,1,4036.3
349,9135358,a,a,d,a,d,a,d,a,a,...,6,2475.8,5,3,2,2,7,7,3,4547.7
350,93418853,d,d,d,a,d,a,d,d,a,...,6,4043.8,9,9,4,8,4,5,4,3643.6
351,LCM83860,d,a,a,a,d,a,d,d,a,...,6,8420.6,4,4,5,5,6,2,4,1222.1
352,Y9815687,a,a,d,a,d,a,d,d,a,...,4,5142.9,5,5,4,3,1,1,3,12659.2

In [ ]:
# Diccionario de mapeo: clave = nombre en df_salience, valor = nombre en df_dims
mapping = {
    "eeuu": "United States",
    "rusia": "Russia",
    "china": "China",
    "singapur": "Singapore",
    "alemania": "Germany",
    "francia": "France",
    "espa√±a": "Spain",
    "marruecos": "Morocco",
    "italia": "Italy",
    "belgica": "Belgium",
    "japon": "Japan",
    "canada": "Canada",
    "noruega": "Norway",
    "ecuador": "Ecuador",
    "brasil": "Brazil",
    "portugal": "Portugal",
    "india": "India",
    "mejico": "Mexico",
    "argentina": "Argentina",
    "uk": "United Kingdom",
    "bielorrusia": "Belarus",
    "luxemburgo": "Luxembourg",
    "andorra": "Andorra",
    "suecia": "Sweden",
    "bulgaria": "Bulgaria",
    "bolivia": "Bolivia",
    "peru": "Peru",
    "eslovenia": "Slovenia",
    "eslovaquia": "Slovakia",
    "paraguay": "Paraguay",
    "yemen": "Yemen",
    "mongolia": "Mongolia",
    "camboya": "Cambodia",
    "uzbekistan": "Uzbekistan",
    "belice": "Belize",
    "ghana": "Ghana",
    "burkina_faso": "Burkina Faso",
    "oman": "Oman",
    "turkmenistan": "Turkmenistan",
    "guayana_francesa": "French Guiana",
    "zimbabue": "Zimbabwe",
    "laos": "Laos",
    "zambia": "Zambia",
    "islas_feroe": "Faroe Islands"
}

## Individual

In [ ]:
df1 = df.copy()
df1

,ID,ghana.luxemburgo_s,turkmeni.uzbeki_s,francia.bolivia_s,belice.eeuu_s,china.luxem_s,laos.mejico_s,rusia.burkinaf_s,francia.belgica_s,andorra.espa√±a_s,...,libano.siria_ABBA,libano.siria_rt_ABBA,brasil.portugal_ABBA,brasil.portugal.1_ABBA,portugal.uruguay_ABBA,coreasur.coreanorte_ABBA,coreanorte.venezuela_ABBA,emirarab.coreanorte_ABBA,coreanorte.yemen_ABBA,brasil.portugal_rt.1_ABBA
0,218713,a,d,d,a,d,a,d,d,a,...,7,3877.2,8,8,5,1,9,3,5,3823.7
1,2319690,a,d,a,a,d,a,d,d,a,...,5,2103.6,4,3,2,1,3,7,6,2718.3
2,2336337,a,d,d,a,d,a,d,d,a,...,7,3437.0,8,7,2,5,1,3,4,4697.3
3,2419139,a,d,d,a,d,a,d,a,a,...,7,4519.3,8,9,2,3,4,6,3,10182.2
4,2563975,a,d,d,a,d,a,d,d,a,...,5,1911.3,9,9,2,2,2,3,1,3063.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,9125906,a,a,d,a,d,a,d,d,d,...,4,3842.8,3,6,6,6,3,7,1,4036.3
349,9135358,a,a,d,a,d,a,d,a,a,...,6,2475.8,5,3,2,2,7,7,3,4547.7
350,93418853,d,d,d,a,d,a,d,d,a,...,6,4043.8,9,9,4,8,4,5,4,3643.6
351,LCM83860,d,a,a,a,d,a,d,d,a,...,6,8420.6,4,4,5,5,6,2,4,1222.1
352,Y9815687,a,a,d,a,d,a,d,d,a,...,4,5142.9,5,5,4,3,1,1,3,12659.2

In [ ]:
# Seleccionar las columnas desde "ghana" hasta "oman"
df1 = df.copy()
columnas_interes = df1.loc[:, "ghana":"oman"]

# Calcular la media de cada columna
media_columnas = columnas_interes.mean().sort_values(ascending=False)

# Mostrar el resultado
print(media_columnas)

eeuu                8.662890
rusia               8.373938
china               8.107649
singapur            8.050992
alemania            7.648725
francia             7.342776
espa√±a             7.150142
marruecos           7.084986
italia              7.053824
belgica             6.169972
japon               6.167139
canada              6.028329
noruega             5.747875
ecuador             5.546742
brasil              5.541076
portugal            5.441926
india               5.419263
mejico              5.325779
argentina           5.192635
uk                  4.988669
bielorrusia         4.433428
luxemburgo          4.297450
andorra             4.033994
suecia              4.005666
bulgaria            3.943343
bolivia             3.691218
peru                3.597734
eslovenia           3.515581
eslovaquia          3.461756
paraguay            3.152975
yemen               2.991501
mongolia            2.614731
camboya             2.543909
uzbekistan          2.337110
belice              2.322946
ghana               2.260623
burkina_faso        2.220963
oman                2.178470
turkmenistan        2.167139
guayana_francesa    2.138810
zimbabue            2.133144
laos                2.127479
zambia              1.963173
islas_feroe         1.835694
dtype: float64

In [ ]:
df1 = df.copy()

# 1) Seleccionamos columnas de interés
columnas_interes = df1.loc[:, "ghana":"oman"]

# 2) Convertimos cada columna a float (quitando '%')
columnas_interes = columnas_interes.apply(
    lambda col: col.astype(str).str.replace('%', '').astype(float)
)

# (Opcional) Si quieres que 8.6% pase a 0.086:
# columnas_interes = columnas_interes / 100

# 3) Calculamos la media
media_columnas = columnas_interes.mean().sort_values(ascending=False)

# 4) Comprobamos tipos y mostramos
print(media_columnas)

eeuu                8.662890
rusia               8.373938
china               8.107649
singapur            8.050992
alemania            7.648725
francia             7.342776
espa√±a             7.150142
marruecos           7.084986
italia              7.053824
belgica             6.169972
japon               6.167139
canada              6.028329
noruega             5.747875
ecuador             5.546742
brasil              5.541076
portugal            5.441926
india               5.419263
mejico              5.325779
argentina           5.192635
uk                  4.988669
bielorrusia         4.433428
luxemburgo          4.297450
andorra             4.033994
suecia              4.005666
bulgaria            3.943343
bolivia             3.691218
peru                3.597734
eslovenia           3.515581
eslovaquia          3.461756
paraguay            3.152975
yemen               2.991501
mongolia            2.614731
camboya             2.543909
uzbekistan          2.337110
belice              2.322946
ghana               2.260623
burkina_faso        2.220963
oman                2.178470
turkmenistan        2.167139
guayana_francesa    2.138810
zimbabue            2.133144
laos                2.127479
zambia              1.963173
islas_feroe         1.835694
dtype: float64

In [ ]:
# Convertir la Serie en DataFrame
df_salience = media_columnas.reset_index()

# Renombrar las columnas para mayor claridad
df_salience.columns = ['pais', 'media']

# Mostrar el nuevo DataFrame
print(df_salience)

                pais     media
0               eeuu  8.662890
1              rusia  8.373938
2              china  8.107649
3           singapur  8.050992
4           alemania  7.648725
5            francia  7.342776
6            espa√±a  7.150142
7          marruecos  7.084986
8             italia  7.053824
9            belgica  6.169972
10             japon  6.167139
11            canada  6.028329
12           noruega  5.747875
13           ecuador  5.546742
14            brasil  5.541076
15          portugal  5.441926
16             india  5.419263
17            mejico  5.325779
18         argentina  5.192635
19                uk  4.988669
20       bielorrusia  4.433428
21        luxemburgo  4.297450
22           andorra  4.033994
23            suecia  4.005666
24          bulgaria  3.943343
25           bolivia  3.691218
26              peru  3.597734
27         eslovenia  3.515581
28        eslovaquia  3.461756
29          paraguay  3.152975
30             yemen  2.991501
31          mongolia  2.614731
32           camboya  2.543909
33        uzbekistan  2.337110
34            belice  2.322946
35             ghana  2.260623
36      burkina_faso  2.220963
37              oman  2.178470
38      turkmenistan  2.167139
39  guayana_francesa  2.138810
40          zimbabue  2.133144
41              laos  2.127479
42            zambia  1.963173
43       islas_feroe  1.835694

In [ ]:
df_salience["pais"] = df_salience["pais"].map(mapping)
df_salience

              pais     media
0    United States  8.662890
1           Russia  8.373938
2            China  8.107649
3        Singapore  8.050992
4          Germany  7.648725
5           France  7.342776
6            Spain  7.150142
7          Morocco  7.084986
8            Italy  7.053824
9          Belgium  6.169972
10           Japan  6.167139
11          Canada  6.028329
12          Norway  5.747875
13         Ecuador  5.546742
14          Brazil  5.541076
15        Portugal  5.441926
16           India  5.419263
17          Mexico  5.325779
18       Argentina  5.192635
19  United Kingdom  4.988669
20         Belarus  4.433428
21      Luxembourg  4.297450
22         Andorra  4.033994
23          Sweden  4.005666
24        Bulgaria  3.943343
25         Bolivia  3.691218
26            Peru  3.597734
27        Slovenia  3.515581
28        Slovakia  3.461756
29        Paraguay  3.152975
30           Yemen  2.991501
31        Mongolia  2.614731
32        Cambodia  2.543909
33      Uzbekistan  2.337110
34          Belize  2.322946
35           Ghana  2.260623
36    Burkina Faso  2.220963
37            Oman  2.178470
38    Turkmenistan  2.167139
39   French Guiana  2.138810
40        Zimbabwe  2.133144
41            Laos  2.127479
42          Zambia  1.963173
43   Faroe Islands  1.835694

## Parejas

In [ ]:
# Filtrar las columnas que siguen el patrón solicitado
start_col = "ghana.luxemburgo_s"
end_col = "oman.yemen_s"
columns_of_interest = df.loc[:, start_col:end_col]

# Contar las ocurrencias de "a" y "d" en cada columna
counts = columns_of_interest.apply(lambda col: col.value_counts()).fillna(0)

# Convertir el índice en una columna para mejor visualización
counts = counts.T.reset_index()
counts.rename(columns={"index": "Relacion", "a": "Cantidad A", "d": "Cantidad D"}, inplace=True)

# Mostrar el DataFrame
display(counts)

                  Relacion  Cantidad A  Cantidad D
0       ghana.luxemburgo_s         294          59
1        turkmeni.uzbeki_s         186         167
2        francia.bolivia_s          44         309
3            belice.eeuu_s         336          17
4            china.luxem_s          49         304
5            laos.mejico_s         305          48
6         rusia.burkinaf_s          31         322
7        francia.belgica_s          97         256
8        andorra.espa√±a_s         336          17
9         china.singapur_s          32         321
10        bielorus.rusia_s         342          11
11        feroe.singapur_s         306          47
12    argentina.paraguay_s          40         313
13        francia.brasil_s         102         251
14       alemania.canada_s         140         213
15          japon.italia_s         106         247
16   argentina.marruecos_s         157         196
17          india.mejico_s         161         192
18        italia.espa√±a_s         238         115
19               uk.eeuu_s         242         111
20        suecia.noruega_s         225         128
21       brasil.portugal_s         187         166
22     burkinaf.guayanaf_s         176         177
23          ecuador.peru_s         204         149
24     mongolia.bulgaria_s         274          79
25           oman.belice_s         178         175
26  eslovenia.eslovaquia_s         183         170
27       zambia.zimbabue_s         217         136
28          laos.camboya_s         224         129
29            oman.yemen_s         213         140

In [ ]:
# Calculate percentages for 'A' and 'D'
counts['Porcentaje A'] = (counts['Cantidad A'] / (counts['Cantidad A'] + counts['Cantidad D'])) * 100
counts['Porcentaje D'] = (counts['Cantidad D'] / (counts['Cantidad A'] + counts['Cantidad D'])) * 100

# Fill NaN values with 0 (if a category is not present in a comparison)
counts.fillna(0, inplace=True)

# Format percentage columns
pd.options.display.float_format = '{:.2f}%'.format

# Display the updated DataFrame
display(counts)

                  Relacion  Cantidad A  Cantidad D  Porcentaje A  Porcentaje D
0       ghana.luxemburgo_s         294          59        83.29%        16.71%
1        turkmeni.uzbeki_s         186         167        52.69%        47.31%
2        francia.bolivia_s          44         309        12.46%        87.54%
3            belice.eeuu_s         336          17        95.18%         4.82%
4            china.luxem_s          49         304        13.88%        86.12%
5            laos.mejico_s         305          48        86.40%        13.60%
6         rusia.burkinaf_s          31         322         8.78%        91.22%
7        francia.belgica_s          97         256        27.48%        72.52%
8        andorra.espa√±a_s         336          17        95.18%         4.82%
9         china.singapur_s          32         321         9.07%        90.93%
10        bielorus.rusia_s         342          11        96.88%         3.12%
11        feroe.singapur_s         306          47        86.69%        13.31%
12    argentina.paraguay_s          40         313        11.33%        88.67%
13        francia.brasil_s         102         251        28.90%        71.10%
14       alemania.canada_s         140         213        39.66%        60.34%
15          japon.italia_s         106         247        30.03%        69.97%
16   argentina.marruecos_s         157         196        44.48%        55.52%
17          india.mejico_s         161         192        45.61%        54.39%
18        italia.espa√±a_s         238         115        67.42%        32.58%
19               uk.eeuu_s         242         111        68.56%        31.44%
20        suecia.noruega_s         225         128        63.74%        36.26%
21       brasil.portugal_s         187         166        52.97%        47.03%
22     burkinaf.guayanaf_s         176         177        49.86%        50.14%
23          ecuador.peru_s         204         149        57.79%        42.21%
24     mongolia.bulgaria_s         274          79        77.62%        22.38%
25           oman.belice_s         178         175        50.42%        49.58%
26  eslovenia.eslovaquia_s         183         170        51.84%        48.16%
27       zambia.zimbabue_s         217         136        61.47%        38.53%
28          laos.camboya_s         224         129        63.46%        36.54%
29            oman.yemen_s         213         140        60.34%        39.66%

In [ ]:
pip install pycountry rapidfuzz

Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Collecting rapidfuzz
  Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 31.2 MB/s eta 0:00:00
Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 23.2 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, pycountry
Successfully installed pycountry-24.6.1 rapidfuzz-3.13.0

In [ ]:
def extraer_texto(row):
    # Se usa la columna "Relacion" renombrada previamente
    relacion = row["Relacion"]
    por_a = row["Porcentaje A"]
    por_d = row["Porcentaje D"]

    if por_a > por_d:
        # Si Porcentaje A es mayor, se extrae el texto entre el punto y el guion bajo
        partes = relacion.split('.')
        if len(partes) > 1:
            return partes[1].split('_')[0]
    elif por_d > por_a:
        # Si Porcentaje D es mayor, se extrae el texto antes del punto
        return relacion.split('.')[0]
    return ""  # En caso de empate o formato inesperado

# Aplicar la función a cada fila y almacenar el resultado en la nueva columna "Pais con mas saliencia"
counts["Pais"] = counts.apply(extraer_texto, axis=1)

# Mostrar el DataFrame final
display(counts)

,Relacion,Cantidad A,Cantidad D,Porcentaje A,Porcentaje D,Pais
0,ghana.luxemburgo_s,294,59,83.29%,16.71%,luxemburgo
1,turkmeni.uzbeki_s,186,167,52.69%,47.31%,uzbeki
2,francia.bolivia_s,44,309,12.46%,87.54%,francia
3,belice.eeuu_s,336,17,95.18%,4.82%,eeuu
4,china.luxem_s,49,304,13.88%,86.12%,china
5,laos.mejico_s,305,48,86.40%,13.60%,mejico
6,rusia.burkinaf_s,31,322,8.78%,91.22%,rusia
7,francia.belgica_s,97,256,27.48%,72.52%,francia
8,andorra.espa√±a_s,336,17,95.18%,4.82%,espa√±a
9,china.singapur_s,32,321,9.07%,90.93%,china
10,bielorus.rusia_s,342,11,96.88%,3.12%,rusia
11,feroe.singapur_s,306,47,86.69%,13.31%,singapur
12,argentina.paraguay_s,40,313,11.33%,88.67%,argentina
13,francia.brasil_s,102,251,28.90%,71.10%,francia
14,alemania.canada_s,140,213,39.66%,60.34%,alemania
15,japon.italia_s,106,247,30.03%,69.97%,japon
16,argentina.marruecos_s,157,196,44.48%,55.52%,argentina
17,india.mejico_s,161,192,45.61%,54.39%,india
18,italia.espa√±a_s,238,115,67.42%,32.58%,espa√±a
19,uk.eeuu_s,242,111,68.56%,31.44%,eeuu
20,suecia.noruega_s,225,128,63.74%,36.26%,noruega
21,brasil.portugal_s,187,166,52.97%,47.03%,portugal
22,burkinaf.guayanaf_s,176,177,49.86%,50.14%,burkinaf
23,ecuador.peru_s,204,149,57.79%,42.21%,peru
24,mongolia.bulgaria_s,274,79,77.62%,22.38%,bulgaria
25,oman.belice_s,178,175,50.42%,49.58%,belice
26,eslovenia.eslovaquia_s,183,170,51.84%,48.16%,eslovaquia
27,zambia.zimbabue_s,217,136,61.47%,38.53%,zimbabue
28,laos.camboya_s,224,129,63.46%,36.54%,camboya
29,oman.yemen_s,213,140,60.34%,39.66%,yemen

In [ ]:
counts_2 = counts
counts_2 = counts_2.rename(columns={
    "Relacion": "Relation",
    "Cantidad A": "Quantity A",
    "Cantidad D": "Quantity D",
    "Porcentaje A": "Percentage A",
    "Porcentaje D": "Percentage D",
    "Pais": "Country"
})
counts_2

,Relation,Quantity A,Quantity D,Percentage A,Percentage D,Country
0,ghana.luxemburgo_s,294,59,83.29%,16.71%,luxemburgo
1,turkmeni.uzbeki_s,186,167,52.69%,47.31%,uzbeki
2,francia.bolivia_s,44,309,12.46%,87.54%,francia
3,belice.eeuu_s,336,17,95.18%,4.82%,eeuu
4,china.luxem_s,49,304,13.88%,86.12%,china
5,laos.mejico_s,305,48,86.40%,13.60%,mejico
6,rusia.burkinaf_s,31,322,8.78%,91.22%,rusia
7,francia.belgica_s,97,256,27.48%,72.52%,francia
8,andorra.espa√±a_s,336,17,95.18%,4.82%,espa√±a
9,china.singapur_s,32,321,9.07%,90.93%,china
10,bielorus.rusia_s,342,11,96.88%,3.12%,rusia
11,feroe.singapur_s,306,47,86.69%,13.31%,singapur
12,argentina.paraguay_s,40,313,11.33%,88.67%,argentina
13,francia.brasil_s,102,251,28.90%,71.10%,francia
14,alemania.canada_s,140,213,39.66%,60.34%,alemania
15,japon.italia_s,106,247,30.03%,69.97%,japon
16,argentina.marruecos_s,157,196,44.48%,55.52%,argentina
17,india.mejico_s,161,192,45.61%,54.39%,india
18,italia.espa√±a_s,238,115,67.42%,32.58%,espa√±a
19,uk.eeuu_s,242,111,68.56%,31.44%,eeuu
20,suecia.noruega_s,225,128,63.74%,36.26%,noruega
21,brasil.portugal_s,187,166,52.97%,47.03%,portugal
22,burkinaf.guayanaf_s,176,177,49.86%,50.14%,burkinaf
23,ecuador.peru_s,204,149,57.79%,42.21%,peru
24,mongolia.bulgaria_s,274,79,77.62%,22.38%,bulgaria
25,oman.belice_s,178,175,50.42%,49.58%,belice
26,eslovenia.eslovaquia_s,183,170,51.84%,48.16%,eslovaquia
27,zambia.zimbabue_s,217,136,61.47%,38.53%,zimbabue
28,laos.camboya_s,224,129,63.46%,36.54%,camboya
29,oman.yemen_s,213,140,60.34%,39.66%,yemen

# Hypothesis 1 (hecha con saliencia individual)

In [ ]:
df2= df.copy()

In [ ]:
df_dims = df_dims.rename(columns={
    'Country': 'pais',
    'Dimensions': 'dimensiones',
    'Subspace': 'subespacio'
})

In [ ]:
df_merged = pd.merge(df_dims, df_salience, on="pais", how="inner")
df_merged = df_merged.rename(columns={"Dimensiones": "dimensions", "media": "salience"})
df_merged['pais'] = df_merged['pais'].str.lower()
df_merged

              pais  dimensiones  subespacio  salience
0            ghana            5         888     2.26%
1           belize            5         806     2.32%
2         slovenia            2         303     3.52%
3         slovakia            4         857     3.46%
4           zambia            4         903     1.96%
5         zimbabwe            6        1670     2.13%
6             laos            3         738     2.13%
7         cambodia            4        1248     2.54%
8            yemen            6        2122     2.99%
9     turkmenistan            4        1024     2.17%
10      uzbekistan            3         717     2.34%
11      luxembourg            6        1401     4.30%
12          france            7        1574     7.34%
13         bolivia            3         694     3.69%
14   united states            7        1241     8.66%
15           china            5         970     8.11%
16          mexico            7        2845     5.33%
17          russia            6        1562     8.37%
18         belgium            4         883     6.17%
19         andorra            5        2128     4.03%
20           spain            6        1277     7.15%
21         belarus            5        1033     4.43%
22   faroe islands            3         792     1.84%
23       argentina            4         922     5.19%
24        paraguay            6        1545     3.15%
25          brazil            6        1937     5.54%
26         germany            6        2243     7.65%
27          canada            7        1038     6.03%
28           japan            8        1749     6.17%
29           italy            6        1512     7.05%
30         morocco            4        1236     7.08%
31           india            8        2381     5.42%
32  united kingdom            4         687     4.99%
33       singapore            7        2032     8.05%
34          sweden            7        1959     4.01%
35          norway            5        1046     5.75%
36        portugal            6        1151     5.44%
37         ecuador            5         798     5.55%
38            peru            6         912     3.60%
39    burkina faso            3         671     2.22%
40   french guiana            3         353     2.14%
41        mongolia            6        1194     2.61%
42        bulgaria            4        1203     3.94%
43            oman            3         578     2.18%

In [ ]:
import pandas as pd

# Diccionario de mapeo: claves en inglés y valores en español
mapping = {
    "ghana": "ghana",
    "belize": "belice",
    "slovenia": "eslovenia",
    "slovakia": "eslovaquia",
    "zambia": "zambia",
    "zimbabwe": "zimbabue",
    "laos": "laos",
    "cambodia": "camboya",
    "turkmenistan": "turkmeni",
    "uzbekistan": "uzbeki",
    "luxembourg": "luxemburgo",
    "france": "francia",
    "bolivia": "bolivia",
    "united states": "eeuu",
    "china": "china",
    "mexico": "mejico",
    "russia": "rusia",
    "belgium": "belgica",
    "andorra": "andorra",
    "spain": "espa√±a",
    "belarus": "bielorus",
    "faroe islands": "feroe",
    "argentina": "argentina",
    "paraguay": "paraguay",
    "brazil": "brasil",
    "canada": "canada",
    "japan": "japon",
    "italy": "italia",
    "morocco": "marruecos",
    "india": "india",
    "united kingdom": "uk",
    "singapore": "singapur",
    "sweden": "suecia",
    "norway": "noruega",
    "portugal": "portugal",
    "ecuador": "ecuador",
    "peru": "peru",
    "burkina faso": "burkinaf",
    "french guiana": "guayanaf",
    "mongolia": "mongolia",
    "bulgaria": "bulgaria",
    "oman": "oman",
    "yemen": "yemen",
    "germany":"alemania"
}

# Actualizamos la columna "pais" en df_merged:
# Convertimos a minúsculas para hacer la búsqueda en el diccionario
df_merged["pais"] = df_merged["pais"].str.lower().map(mapping)

# Si algún país no se encontró en el mapping, se puede dejar el valor original o asignarle un valor predeterminado.
# Por ejemplo, para reemplazar valores faltantes con el valor original:
df_merged["pais"] = df_merged["pais"].fillna(df_merged["pais"])
df_merged['salience'] = df_merged['salience'].astype(str).str.replace('%', '').astype(float)

# Mostramos el DataFrame actualizado
df_merged

          pais  dimensiones  subespacio  salience
0        ghana            5         888     2.26%
1       belice            5         806     2.32%
2    eslovenia            2         303     3.52%
3   eslovaquia            4         857     3.46%
4       zambia            4         903     1.96%
5     zimbabue            6        1670     2.13%
6         laos            3         738     2.13%
7      camboya            4        1248     2.54%
8        yemen            6        2122     2.99%
9     turkmeni            4        1024     2.17%
10      uzbeki            3         717     2.34%
11  luxemburgo            6        1401     4.30%
12     francia            7        1574     7.34%
13     bolivia            3         694     3.69%
14        eeuu            7        1241     8.66%
15       china            5         970     8.11%
16      mejico            7        2845     5.33%
17       rusia            6        1562     8.37%
18     belgica            4         883     6.17%
19     andorra            5        2128     4.03%
20     espa√±a            6        1277     7.15%
21    bielorus            5        1033     4.43%
22       feroe            3         792     1.84%
23   argentina            4         922     5.19%
24    paraguay            6        1545     3.15%
25      brasil            6        1937     5.54%
26    alemania            6        2243     7.65%
27      canada            7        1038     6.03%
28       japon            8        1749     6.17%
29      italia            6        1512     7.05%
30   marruecos            4        1236     7.08%
31       india            8        2381     5.42%
32          uk            4         687     4.99%
33    singapur            7        2032     8.05%
34      suecia            7        1959     4.01%
35     noruega            5        1046     5.75%
36    portugal            6        1151     5.44%
37     ecuador            5         798     5.55%
38        peru            6         912     3.60%
39    burkinaf            3         671     2.22%
40    guayanaf            3         353     2.14%
41    mongolia            6        1194     2.61%
42    bulgaria            4        1203     3.94%
43        oman            3         578     2.18%

In [ ]:
import pandas as pd
pd.reset_option('display.float_format')
print(df_merged['salience'].head())

0    2.260623
1    2.322946
2    3.515581
3    3.461756
4    1.963173
Name: salience, dtype: float64

In [ ]:
df_merged

          pais  dimensiones  subespacio  salience
0        ghana            5         888  2.260623
1       belice            5         806  2.322946
2    eslovenia            2         303  3.515581
3   eslovaquia            4         857  3.461756
4       zambia            4         903  1.963173
5     zimbabue            6        1670  2.133144
6         laos            3         738  2.127479
7      camboya            4        1248  2.543909
8        yemen            6        2122  2.991501
9     turkmeni            4        1024  2.167139
10      uzbeki            3         717  2.337110
11  luxemburgo            6        1401  4.297450
12     francia            7        1574  7.342776
13     bolivia            3         694  3.691218
14        eeuu            7        1241  8.662890
15       china            5         970  8.107649
16      mejico            7        2845  5.325779
17       rusia            6        1562  8.373938
18     belgica            4         883  6.169972
19     andorra            5        2128  4.033994
20     espa√±a            6        1277  7.150142
21    bielorus            5        1033  4.433428
22       feroe            3         792  1.835694
23   argentina            4         922  5.192635
24    paraguay            6        1545  3.152975
25      brasil            6        1937  5.541076
26    alemania            6        2243  7.648725
27      canada            7        1038  6.028329
28       japon            8        1749  6.167139
29      italia            6        1512  7.053824
30   marruecos            4        1236  7.084986
31       india            8        2381  5.419263
32          uk            4         687  4.988669
33    singapur            7        2032  8.050992
34      suecia            7        1959  4.005666
35     noruega            5        1046  5.747875
36    portugal            6        1151  5.441926
37     ecuador            5         798  5.546742
38        peru            6         912  3.597734
39    burkinaf            3         671  2.220963
40    guayanaf            3         353  2.138810
41    mongolia            6        1194  2.614731
42    bulgaria            4        1203  3.943343
43        oman            3         578  2.178470

In [ ]:
start_col = "ghana.luxemburgo_s"
end_col = "oman.yemen_s"
columns_of_interest = df2.loc[:, start_col:end_col]
columns_of_interest.rename(columns={'china.luxem_s': 'china.luxemburgo_s'}, inplace=True)
columns_of_interest

,ghana.luxemburgo_s,turkmeni.uzbeki_s,francia.bolivia_s,belice.eeuu_s,china.luxemburgo_s,laos.mejico_s,rusia.burkinaf_s,francia.belgica_s,andorra.espa√±a_s,china.singapur_s,...,suecia.noruega_s,brasil.portugal_s,burkinaf.guayanaf_s,ecuador.peru_s,mongolia.bulgaria_s,oman.belice_s,eslovenia.eslovaquia_s,zambia.zimbabue_s,laos.camboya_s,oman.yemen_s
0,a,d,d,a,d,a,d,d,a,d,...,a,a,a,d,a,a,a,a,a,a
1,a,d,a,a,d,a,d,d,a,d,...,a,d,d,d,d,a,d,a,a,a
2,a,d,d,a,d,a,d,d,a,d,...,a,a,d,a,d,d,d,a,a,d
3,a,d,d,a,d,a,d,a,a,d,...,d,a,a,a,a,a,d,a,a,a
4,a,d,d,a,d,a,d,d,a,d,...,d,a,a,a,a,d,d,a,d,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,a,a,d,a,d,a,d,d,d,d,...,d,d,d,a,a,d,d,d,a,d
349,a,a,d,a,d,a,d,a,a,d,...,d,a,d,a,a,d,d,d,a,a
350,d,d,d,a,d,a,d,d,a,d,...,a,a,d,d,d,a,d,d,a,a
351,d,a,a,a,d,a,d,d,a,d,...,a,a,d,d,d,d,d,d,d,a
352,a,a,d,a,d,a,d,d,a,d,...,d,d,d,a,a,a,d,a,a,a

In [ ]:
pair_results = []
for col in columns_of_interest.columns:
    # Suponemos que el nombre de la columna tiene el formato "pais1.pais2_s"
    base = col.split('_')[0]  # e.g., "ghana.luxembourg"
    try:
        c1, c2 = base.split('.')
    except Exception as e:
        print(f"Error al procesar el formato de la columna '{col}': {e}")
        continue

    c1_mapped = mapping.get(c1, c1.title())
    c2_mapped = mapping.get(c2, c2.title())

    # Buscar en df_merged usando comparaciones en minúsculas para mayor robustez
    row_c1 = df_merged.loc[df_merged["pais"].str.lower() == c1_mapped.lower()]
    row_c2 = df_merged.loc[df_merged["pais"].str.lower() == c2_mapped.lower()]

    # Si alguna de las filas no se encuentra, se omite este par
    if row_c1.empty or row_c2.empty:
        print(f"Mapping no encontrado para '{c1_mapped}' o '{c2_mapped}' en df_merged. Se omite el par '{col}'.")
        continue

    s1 = row_c1["salience"].values[0]
    s2 = row_c2["salience"].values[0]
    d1 = row_c1["dimensiones"].values[0]
    d2 = row_c2["dimensiones"].values[0]

    # Comprobar consistencia: si s1 > s2 esperamos d1 > d2, y viceversa
    if (s1 > s2 and d1 > d2) or (s2 > s1 and d2 > d1):
        consistency = True
    else:
        consistency = False

    pair_results.append({
        "Pair": f"{c1_mapped} vs {c2_mapped}",
        "Salience A": round(s1,2),
        "Salience D": round(s2,2),
        "Dimensions A": d1,
        "Dimensions D": d2,
        "Consistent": consistency
    })

df_pairs = pd.DataFrame(pair_results)
df_pairs

,Pair,Salience A,Salience D,Dimensions A,Dimensions D,Consistent
0,ghana vs Luxemburgo,2.26,4.30,5,6,True
1,Turkmeni vs Uzbeki,2.17,2.34,4,3,False
2,Francia vs bolivia,7.34,3.69,7,3,True
3,Belice vs Eeuu,2.32,8.66,5,7,True
4,china vs Luxemburgo,8.11,4.30,5,6,False
5,laos vs Mejico,2.13,5.33,3,7,True
6,Rusia vs Burkinaf,8.37,2.22,6,3,True
7,Francia vs Belgica,7.34,6.17,7,4,True
8,andorra vs Espa√±A,4.03,7.15,5,6,True
9,china vs Singapur,8.11,8.05,5,7,False
10,Bielorus vs Rusia,4.43,8.37,5,6,True
11,Feroe vs Singapur,1.84,8.05,3,7,True
12,argentina vs paraguay,5.19,3.15,4,6,False
13,Francia vs Brasil,7.34,5.54,7,6,True
14,Alemania vs canada,7.65,6.03,6,7,False
15,Japon vs Italia,6.17,7.05,8,6,False
16,argentina vs Marruecos,5.19,7.08,4,4,False
17,india vs Mejico,5.42,5.33,8,7,True
18,Italia vs Espa√±A,7.05,7.15,6,6,False
19,Uk vs Eeuu,4.99,8.66,4,7,True
20,Suecia vs Noruega,4.01,5.75,7,5,False
21,Brasil vs portugal,5.54,5.44,6,6,False
22,Burkinaf vs Guayanaf,2.22,2.14,3,3,False
23,ecuador vs peru,5.55,3.60,5,6,False
24,mongolia vs bulgaria,2.61,3.94,6,4,False
25,oman vs Belice,2.18,2.32,3,5,True
26,Eslovenia vs Eslovaquia,3.52,3.46,2,4,False
27,zambia vs Zimbabue,1.96,2.13,4,6,True
28,laos vs Camboya,2.13,2.54,3,4,True
29,oman vs yemen,2.18,2.99,3,6,True

In [ ]:
conteo = df_pairs['Consistent'].value_counts()
print(conteo)

Consistent
True     16
False    14
Name: count, dtype: int64

# Hypothesis 1

In [ ]:
import pandas as pd

# --- 1. Diccionario para convertir nombres de df_dims (inglés) a español ---
mapping_en_to_es = {
    "ghana": "ghana",
    "belize": "belice",
    "slovenia": "eslovenia",
    "slovakia": "eslovaquia",
    "zambia": "zambia",
    "zimbabwe": "zimbabue",
    "laos": "laos",
    "cambodia": "camboya",
    "turkmenistan": "turkmeni",
    "uzbekistan": "uzbeki",
    "luxembourg": "luxemburgo",
    "france": "francia",
    "bolivia": "bolivia",
    "united states": "eeuu",
    "china": "china",
    "mexico": "mejico",
    "russia": "rusia",
    "belgium": "belgica",
    "andorra": "andorra",
    "spain": "espa√±a",
    "belarus": "bielorus",
    "faroe islands": "feroe",
    "argentina": "argentina",
    "paraguay": "paraguay",
    "brazil": "brasil",
    "canada": "canada",
    "japan": "japon",
    "italy": "italia",
    "morocco": "marruecos",
    "india": "india",
    "united kingdom": "uk",
    "singapore": "singapur",
    "sweden": "suecia",
    "norway": "noruega",
    "portugal": "portugal",
    "ecuador": "ecuador",
    "peru": "peru",
    "burkina faso": "burkinaf",
    "french guiana": "guayanaf",
    "mongolia": "mongolia",
    "bulgaria": "bulgaria",
    "oman": "oman",
    "yemen": "yemen",
    "germany":"alemania"
}

df_dims_2 = df_dims.copy()
# --- 2. Actualizar df_dims para tener nombres en español ---
# Suponiendo que df_dims tiene las columnas "pais" y "dimensions"
df_dims_2["pais"] = df_dims_2["pais"].str.lower().map(mapping_en_to_es)

# Si algún valor no se mapeó, opcionalmente se puede conservar el original:
df_dims_2["pais"] = df_dims_2["pais"].fillna(df_dims_2["pais"].str.lower())
df_dims_2

          pais  dimensiones  subespacio
0        ghana            5         888
1       belice            5         806
2    eslovenia            2         303
3   eslovaquia            4         857
4       zambia            4         903
5     zimbabue            6        1670
6         laos            3         738
7      camboya            4        1248
8        yemen            6        2122
9     turkmeni            4        1024
10      uzbeki            3         717
11  luxemburgo            6        1401
12     francia            7        1574
13     bolivia            3         694
14        eeuu            7        1241
15       china            5         970
16      mejico            7        2845
17       rusia            6        1562
18     belgica            4         883
19     andorra            5        2128
20     espa√±a            6        1277
21    bielorus            5        1033
22       feroe            3         792
23   argentina            4         922
24    paraguay            6        1545
25      brasil            6        1937
26    alemania            6        2243
27      canada            7        1038
28       japon            8        1749
29      italia            6        1512
30   marruecos            4        1236
31       india            8        2381
32          uk            4         687
33    singapur            7        2032
34      suecia            7        1959
35     noruega            5        1046
36    portugal            6        1151
37     ecuador            5         798
38        peru            6         912
39    burkinaf            3         671
40    guayanaf            3         353
41    mongolia            6        1194
42    bulgaria            4        1203
43        oman            3         578

In [ ]:
counts

,Relacion,Cantidad A,Cantidad D,Porcentaje A,Porcentaje D,Pais
0,ghana.luxemburgo_s,294,59,83.286119,16.713881,luxemburgo
1,turkmeni.uzbeki_s,186,167,52.691218,47.308782,uzbeki
2,francia.bolivia_s,44,309,12.464589,87.535411,francia
3,belice.eeuu_s,336,17,95.184136,4.815864,eeuu
4,china.luxem_s,49,304,13.881020,86.118980,china
5,laos.mejico_s,305,48,86.402266,13.597734,mejico
6,rusia.burkinaf_s,31,322,8.781870,91.218130,rusia
7,francia.belgica_s,97,256,27.478754,72.521246,francia
8,andorra.espa√±a_s,336,17,95.184136,4.815864,espa√±a
9,china.singapur_s,32,321,9.065156,90.934844,china
10,bielorus.rusia_s,342,11,96.883853,3.116147,rusia
11,feroe.singapur_s,306,47,86.685552,13.314448,singapur
12,argentina.paraguay_s,40,313,11.331445,88.668555,argentina
13,francia.brasil_s,102,251,28.895184,71.104816,francia
14,alemania.canada_s,140,213,39.660057,60.339943,alemania
15,japon.italia_s,106,247,30.028329,69.971671,japon
16,argentina.marruecos_s,157,196,44.475921,55.524079,argentina
17,india.mejico_s,161,192,45.609065,54.390935,india
18,italia.espa√±a_s,238,115,67.422096,32.577904,espa√±a
19,uk.eeuu_s,242,111,68.555241,31.444759,eeuu
20,suecia.noruega_s,225,128,63.739377,36.260623,noruega
21,brasil.portugal_s,187,166,52.974504,47.025496,portugal
22,burkinaf.guayanaf_s,176,177,49.858357,50.141643,burkinaf
23,ecuador.peru_s,204,149,57.790368,42.209632,peru
24,mongolia.bulgaria_s,274,79,77.620397,22.379603,bulgaria
25,oman.belice_s,178,175,50.424929,49.575071,belice
26,eslovenia.eslovaquia_s,183,170,51.841360,48.158640,eslovaquia
27,zambia.zimbabue_s,217,136,61.473088,38.526912,zimbabue
28,laos.camboya_s,224,129,63.456091,36.543909,camboya
29,oman.yemen_s,213,140,60.339943,39.660057,yemen

In [ ]:
counts["Relacion"] = counts["Relacion"].replace("china.luxem_s", "china.luxemburgo_s")

In [ ]:
counts

,Relacion,Cantidad A,Cantidad D,Porcentaje A,Porcentaje D,Pais
0,ghana.luxemburgo_s,294,59,83.286119,16.713881,luxemburgo
1,turkmeni.uzbeki_s,186,167,52.691218,47.308782,uzbeki
2,francia.bolivia_s,44,309,12.464589,87.535411,francia
3,belice.eeuu_s,336,17,95.184136,4.815864,eeuu
4,china.luxemburgo_s,49,304,13.881020,86.118980,china
5,laos.mejico_s,305,48,86.402266,13.597734,mejico
6,rusia.burkinaf_s,31,322,8.781870,91.218130,rusia
7,francia.belgica_s,97,256,27.478754,72.521246,francia
8,andorra.espa√±a_s,336,17,95.184136,4.815864,espa√±a
9,china.singapur_s,32,321,9.065156,90.934844,china
10,bielorus.rusia_s,342,11,96.883853,3.116147,rusia
11,feroe.singapur_s,306,47,86.685552,13.314448,singapur
12,argentina.paraguay_s,40,313,11.331445,88.668555,argentina
13,francia.brasil_s,102,251,28.895184,71.104816,francia
14,alemania.canada_s,140,213,39.660057,60.339943,alemania
15,japon.italia_s,106,247,30.028329,69.971671,japon
16,argentina.marruecos_s,157,196,44.475921,55.524079,argentina
17,india.mejico_s,161,192,45.609065,54.390935,india
18,italia.espa√±a_s,238,115,67.422096,32.577904,espa√±a
19,uk.eeuu_s,242,111,68.555241,31.444759,eeuu
20,suecia.noruega_s,225,128,63.739377,36.260623,noruega
21,brasil.portugal_s,187,166,52.974504,47.025496,portugal
22,burkinaf.guayanaf_s,176,177,49.858357,50.141643,burkinaf
23,ecuador.peru_s,204,149,57.790368,42.209632,peru
24,mongolia.bulgaria_s,274,79,77.620397,22.379603,bulgaria
25,oman.belice_s,178,175,50.424929,49.575071,belice
26,eslovenia.eslovaquia_s,183,170,51.841360,48.158640,eslovaquia
27,zambia.zimbabue_s,217,136,61.473088,38.526912,zimbabue
28,laos.camboya_s,224,129,63.456091,36.543909,camboya
29,oman.yemen_s,213,140,60.339943,39.660057,yemen

## Sin nada

In [ ]:


# --- 3. Procesar df_table para comparar la saliencia y dimensiones ---
# Suponemos que df_table tiene:
# - La columna "Relación" con el formato "pais1.pais2_s" (por ejemplo, "ghana.luxemburgo_s")
# - La columna "Pais" con el país considerado más saliente (en español, por ejemplo, "luxemburgo")

# Creamos la columna "Consistente" en df_table
counts["Consistente"] = False

# Recorremos cada fila de counts
for idx, row in counts.iterrows():
    relacion = row["Relacion"]   # Ej: "ghana.luxemburgo_s"
    pais_saliente = row["Pais"]  # Ej: "luxemburgo"

    # Extraemos la parte antes de "_s"
    base = relacion.split("_")[0]  # "ghana.luxemburgo"
    try:
        pais1, pais2 = base.split(".")
    except ValueError:
        # Si no se puede separar correctamente, se omite la fila
        continue

    # Convertimos a minúsculas para comparar
    pais1 = pais1.lower()
    pais2 = pais2.lower()
    pais_saliente = pais_saliente.lower()

    # Determinamos cuál es el otro país según la columna "Pais"
    if pais_saliente == pais1:
        otro = pais2
    elif pais_saliente == pais2:
        otro = pais1
    else:
        # Si el país saliente no coincide con ninguno de los dos, se omite la fila
        continue

    # Buscamos en df_dims (usamos la columna "pais_es" en df_dims, que contiene los nombres en español)
    dims_saliente_arr = df_dims_2.loc[df_dims_2["pais"] == pais_saliente, "dimensiones"].values
    dims_otro_arr = df_dims_2.loc[df_dims_2["pais"] == otro, "dimensiones"].values

    # Verificamos que se encontraron datos para ambos países
    if len(dims_saliente_arr) == 0 or len(dims_otro_arr) == 0:
        continue

    dims_saliente = dims_saliente_arr[0]
    dims_otro = dims_otro_arr[0]

    # Se espera que el país saliente tenga más dimensiones que el otro
    if dims_saliente > dims_otro:
        counts.at[idx, "Consistente"] = True

# Visualizamos el resultado (columnas "Relación", "Pais" y "Consistente")
print(counts[["Relacion", "Pais", "Consistente"]])

                  Relacion        Pais  Consistente
0       ghana.luxemburgo_s  luxemburgo         True
1        turkmeni.uzbeki_s      uzbeki        False
2        francia.bolivia_s     francia         True
3            belice.eeuu_s        eeuu         True
4       china.luxemburgo_s       china        False
5            laos.mejico_s      mejico         True
6         rusia.burkinaf_s       rusia         True
7        francia.belgica_s     francia         True
8        andorra.espa√±a_s     espa√±a         True
9         china.singapur_s       china        False
10        bielorus.rusia_s       rusia         True
11        feroe.singapur_s    singapur         True
12    argentina.paraguay_s   argentina        False
13        francia.brasil_s     francia         True
14       alemania.canada_s    alemania        False
15          japon.italia_s       japon         True
16   argentina.marruecos_s   argentina        False
17          india.mejico_s       india         True
18        italia.espa√±a_s     espa√±a        False
19               uk.eeuu_s        eeuu         True
20        suecia.noruega_s     noruega        False
21       brasil.portugal_s    portugal        False
22     burkinaf.guayanaf_s    burkinaf        False
23          ecuador.peru_s        peru         True
24     mongolia.bulgaria_s    bulgaria        False
25           oman.belice_s      belice         True
26  eslovenia.eslovaquia_s  eslovaquia         True
27       zambia.zimbabue_s    zimbabue         True
28          laos.camboya_s     camboya         True
29            oman.yemen_s       yemen         True

## Con dimesnsiones

In [ ]:
# --- 3. Procesar counts para comparar la saliencia y dimensiones ---
# Suponemos que counts tiene:
# - La columna "Relacion" con el formato "pais1.pais2_s" (por ejemplo, "ghana.luxemburgo_s")
# - La columna "Pais" con el país considerado más saliente (en español, por ejemplo, "luxemburgo")
# Y que df_dim_2 tiene las columnas "pais" y "Dimensiones"

# Creamos las columnas "Consistente", "Dim_saliente" y "Dim_otro" en counts
counts["Consistente"] = False
counts["Dim_saliente"] = None
counts["Dim_otro"] = None

for idx, row in counts.iterrows():
    relacion = row["Relacion"]   # Ej: "ghana.luxemburgo_s"
    pais_saliente = row["Pais"]  # Ej: "luxemburgo"

    # Extraemos la parte antes de "_s"
    base = relacion.split("_")[0]  # "ghana.luxemburgo"
    try:
        pais1, pais2 = base.split(".")
    except ValueError:
        # Si no se puede separar correctamente, se omite la fila
        continue

    # Convertimos a minúsculas para comparar
    pais1 = pais1.lower()
    pais2 = pais2.lower()
    pais_saliente = pais_saliente.lower()

    # Determinamos cuál es el otro país según la columna "Pais"
    if pais_saliente == pais1:
        otro = pais2
    elif pais_saliente == pais2:
        otro = pais1
    else:
        # Si el país saliente no coincide con ninguno de los dos, se omite la fila
        continue

    # Buscamos en df_dim_2 (usamos la columna "pais" en df_dim_2, que contiene los nombres en español)
    dims_saliente_arr = df_dims_2.loc[df_dims_2["pais"] == pais_saliente, "dimensiones"].values
    dims_otro_arr = df_dims_2.loc[df_dims_2["pais"] == otro, "dimensiones"].values

    # Verificamos que se encontraron datos para ambos países
    if len(dims_saliente_arr) == 0 or len(dims_otro_arr) == 0:
        continue

    dims_saliente = dims_saliente_arr[0]
    dims_otro = dims_otro_arr[0]

    # Añadimos las dimensiones en las nuevas columnas
    counts.at[idx, "Dim_saliente"] = dims_saliente
    counts.at[idx, "Dim_otro"] = dims_otro

    # Se espera que el país saliente tenga más dimensiones que el otro
    if dims_saliente > dims_otro:
        counts.at[idx, "Consistente"] = True

# Visualizamos el resultado (se muestran las columnas "Relacion", "Pais", "Dim_saliente", "Dim_otro" y "Consistente")
print(counts[["Relacion", "Pais", "Dim_saliente", "Dim_otro", "Consistente"]])

                  Relacion        Pais Dim_saliente Dim_otro  Consistente
0       ghana.luxemburgo_s  luxemburgo            6        5         True
1        turkmeni.uzbeki_s      uzbeki            3        4        False
2        francia.bolivia_s     francia            7        3         True
3            belice.eeuu_s        eeuu            7        5         True
4       china.luxemburgo_s       china            5        6        False
5            laos.mejico_s      mejico            7        3         True
6         rusia.burkinaf_s       rusia            6        3         True
7        francia.belgica_s     francia            7        4         True
8        andorra.espa√±a_s     espa√±a            6        5         True
9         china.singapur_s       china            5        7        False
10        bielorus.rusia_s       rusia            6        5         True
11        feroe.singapur_s    singapur            7        3         True
12    argentina.paraguay_s   argentina            4        6        False
13        francia.brasil_s     francia            7        6         True
14       alemania.canada_s    alemania            6        7        False
15          japon.italia_s       japon            8        6         True
16   argentina.marruecos_s   argentina            4        4        False
17          india.mejico_s       india            8        7         True
18        italia.espa√±a_s     espa√±a            6        6        False
19               uk.eeuu_s        eeuu            7        4         True
20        suecia.noruega_s     noruega            5        7        False
21       brasil.portugal_s    portugal            6        6        False
22     burkinaf.guayanaf_s    burkinaf            3        3        False
23          ecuador.peru_s        peru            6        5         True
24     mongolia.bulgaria_s    bulgaria            4        6        False
25           oman.belice_s      belice            5        3         True
26  eslovenia.eslovaquia_s  eslovaquia            4        2         True
27       zambia.zimbabue_s    zimbabue            6        4         True
28          laos.camboya_s     camboya            4        3         True
29            oman.yemen_s       yemen            6        3         True

## Con dimensiones y saliencia

In [ ]:
counts

,Relacion,Cantidad A,Cantidad D,Porcentaje A,Porcentaje D,Pais,Consistente,Dim_saliente,Dim_otro
0,ghana.luxemburgo_s,294,59,83.286119,16.713881,luxemburgo,True,6,5
1,turkmeni.uzbeki_s,186,167,52.691218,47.308782,uzbeki,False,3,4
2,francia.bolivia_s,44,309,12.464589,87.535411,francia,True,7,3
3,belice.eeuu_s,336,17,95.184136,4.815864,eeuu,True,7,5
4,china.luxemburgo_s,49,304,13.881020,86.118980,china,False,5,6
5,laos.mejico_s,305,48,86.402266,13.597734,mejico,True,7,3
6,rusia.burkinaf_s,31,322,8.781870,91.218130,rusia,True,6,3
7,francia.belgica_s,97,256,27.478754,72.521246,francia,True,7,4
8,andorra.espa√±a_s,336,17,95.184136,4.815864,espa√±a,True,6,5
9,china.singapur_s,32,321,9.065156,90.934844,china,False,5,7
10,bielorus.rusia_s,342,11,96.883853,3.116147,rusia,True,6,5
11,feroe.singapur_s,306,47,86.685552,13.314448,singapur,True,7,3
12,argentina.paraguay_s,40,313,11.331445,88.668555,argentina,False,4,6
13,francia.brasil_s,102,251,28.895184,71.104816,francia,True,7,6
14,alemania.canada_s,140,213,39.660057,60.339943,alemania,False,6,7
15,japon.italia_s,106,247,30.028329,69.971671,japon,True,8,6
16,argentina.marruecos_s,157,196,44.475921,55.524079,argentina,False,4,4
17,india.mejico_s,161,192,45.609065,54.390935,india,True,8,7
18,italia.espa√±a_s,238,115,67.422096,32.577904,espa√±a,False,6,6
19,uk.eeuu_s,242,111,68.555241,31.444759,eeuu,True,7,4
20,suecia.noruega_s,225,128,63.739377,36.260623,noruega,False,5,7
21,brasil.portugal_s,187,166,52.974504,47.025496,portugal,False,6,6
22,burkinaf.guayanaf_s,176,177,49.858357,50.141643,burkinaf,False,3,3
23,ecuador.peru_s,204,149,57.790368,42.209632,peru,True,6,5
24,mongolia.bulgaria_s,274,79,77.620397,22.379603,bulgaria,False,4,6
25,oman.belice_s,178,175,50.424929,49.575071,belice,True,5,3
26,eslovenia.eslovaquia_s,183,170,51.841360,48.158640,eslovaquia,True,4,2
27,zambia.zimbabue_s,217,136,61.473088,38.526912,zimbabue,True,6,4
28,laos.camboya_s,224,129,63.456091,36.543909,camboya,True,4,3
29,oman.yemen_s,213,140,60.339943,39.660057,yemen,True,6,3

In [ ]:
counts = counts.rename(columns={
    "Relacion": "Relation",
    "Cantidad A": "Quantity A",
    "Cantidad D": "Quantity D",
    "Porcentaje A": "Percentage A",
    "Porcentaje D": "Percentage D",
    "Pais": "Country",
    "Consistente": "Consistent",
    "Dim_saliente": "Prominent Dimension",
    "Dim_otro": "Other Dimension"
})
counts['Percentage A'] = counts['Percentage A'].apply(lambda x: "{:.2f}%".format(x))
counts['Percentage D'] = counts['Percentage D'].apply(lambda x: "{:.2f}%".format(x))

counts

,Relation,Quantity A,Quantity D,Percentage A,Percentage D,Country,Consistent,Prominent Dimension,Other Dimension
0,ghana.luxemburgo_s,294,59,83.29%,16.71%,luxemburgo,True,6,5
1,turkmeni.uzbeki_s,186,167,52.69%,47.31%,uzbeki,False,3,4
2,francia.bolivia_s,44,309,12.46%,87.54%,francia,True,7,3
3,belice.eeuu_s,336,17,95.18%,4.82%,eeuu,True,7,5
4,china.luxemburgo_s,49,304,13.88%,86.12%,china,False,5,6
5,laos.mejico_s,305,48,86.40%,13.60%,mejico,True,7,3
6,rusia.burkinaf_s,31,322,8.78%,91.22%,rusia,True,6,3
7,francia.belgica_s,97,256,27.48%,72.52%,francia,True,7,4
8,andorra.espa√±a_s,336,17,95.18%,4.82%,espa√±a,True,6,5
9,china.singapur_s,32,321,9.07%,90.93%,china,False,5,7
10,bielorus.rusia_s,342,11,96.88%,3.12%,rusia,True,6,5
11,feroe.singapur_s,306,47,86.69%,13.31%,singapur,True,7,3
12,argentina.paraguay_s,40,313,11.33%,88.67%,argentina,False,4,6
13,francia.brasil_s,102,251,28.90%,71.10%,francia,True,7,6
14,alemania.canada_s,140,213,39.66%,60.34%,alemania,False,6,7
15,japon.italia_s,106,247,30.03%,69.97%,japon,True,8,6
16,argentina.marruecos_s,157,196,44.48%,55.52%,argentina,False,4,4
17,india.mejico_s,161,192,45.61%,54.39%,india,True,8,7
18,italia.espa√±a_s,238,115,67.42%,32.58%,espa√±a,False,6,6
19,uk.eeuu_s,242,111,68.56%,31.44%,eeuu,True,7,4
20,suecia.noruega_s,225,128,63.74%,36.26%,noruega,False,5,7
21,brasil.portugal_s,187,166,52.97%,47.03%,portugal,False,6,6
22,burkinaf.guayanaf_s,176,177,49.86%,50.14%,burkinaf,False,3,3
23,ecuador.peru_s,204,149,57.79%,42.21%,peru,True,6,5
24,mongolia.bulgaria_s,274,79,77.62%,22.38%,bulgaria,False,4,6
25,oman.belice_s,178,175,50.42%,49.58%,belice,True,5,3
26,eslovenia.eslovaquia_s,183,170,51.84%,48.16%,eslovaquia,True,4,2
27,zambia.zimbabue_s,217,136,61.47%,38.53%,zimbabue,True,6,4
28,laos.camboya_s,224,129,63.46%,36.54%,camboya,True,4,3
29,oman.yemen_s,213,140,60.34%,39.66%,yemen,True,6,3

In [ ]:
conteo = counts['Consistent'].value_counts()
print(conteo)

Consistent
True     19
False    11
Name: count, dtype: int64

In [ ]:

counts.loc[:, "Relation":"Percentage D"]

                  Relation  Quantity A  Quantity D Percentage A Percentage D
0       ghana.luxemburgo_s         294          59       83.29%       16.71%
1        turkmeni.uzbeki_s         186         167       52.69%       47.31%
2        francia.bolivia_s          44         309       12.46%       87.54%
3            belice.eeuu_s         336          17       95.18%        4.82%
4       china.luxemburgo_s          49         304       13.88%       86.12%
5            laos.mejico_s         305          48       86.40%       13.60%
6         rusia.burkinaf_s          31         322        8.78%       91.22%
7        francia.belgica_s          97         256       27.48%       72.52%
8        andorra.espa√±a_s         336          17       95.18%        4.82%
9         china.singapur_s          32         321        9.07%       90.93%
10        bielorus.rusia_s         342          11       96.88%        3.12%
11        feroe.singapur_s         306          47       86.69%       13.31%
12    argentina.paraguay_s          40         313       11.33%       88.67%
13        francia.brasil_s         102         251       28.90%       71.10%
14       alemania.canada_s         140         213       39.66%       60.34%
15          japon.italia_s         106         247       30.03%       69.97%
16   argentina.marruecos_s         157         196       44.48%       55.52%
17          india.mejico_s         161         192       45.61%       54.39%
18        italia.espa√±a_s         238         115       67.42%       32.58%
19               uk.eeuu_s         242         111       68.56%       31.44%
20        suecia.noruega_s         225         128       63.74%       36.26%
21       brasil.portugal_s         187         166       52.97%       47.03%
22     burkinaf.guayanaf_s         176         177       49.86%       50.14%
23          ecuador.peru_s         204         149       57.79%       42.21%
24     mongolia.bulgaria_s         274          79       77.62%       22.38%
25           oman.belice_s         178         175       50.42%       49.58%
26  eslovenia.eslovaquia_s         183         170       51.84%       48.16%
27       zambia.zimbabue_s         217         136       61.47%       38.53%
28          laos.camboya_s         224         129       63.46%       36.54%
29            oman.yemen_s         213         140       60.34%       39.66%

# Hypothesis 2

In [ ]:
df_merged

          pais  dimensiones  subespacio  salience
0        ghana            5         888  2.260623
1       belice            5         806  2.322946
2    eslovenia            2         303  3.515581
3   eslovaquia            4         857  3.461756
4       zambia            4         903  1.963173
5     zimbabue            6        1670  2.133144
6         laos            3         738  2.127479
7      camboya            4        1248  2.543909
8        yemen            6        2122  2.991501
9     turkmeni            4        1024  2.167139
10      uzbeki            3         717  2.337110
11  luxemburgo            6        1401  4.297450
12     francia            7        1574  7.342776
13     bolivia            3         694  3.691218
14        eeuu            7        1241  8.662890
15       china            5         970  8.107649
16      mejico            7        2845  5.325779
17       rusia            6        1562  8.373938
18     belgica            4         883  6.169972
19     andorra            5        2128  4.033994
20     espa√±a            6        1277  7.150142
21    bielorus            5        1033  4.433428
22       feroe            3         792  1.835694
23   argentina            4         922  5.192635
24    paraguay            6        1545  3.152975
25      brasil            6        1937  5.541076
26    alemania            6        2243  7.648725
27      canada            7        1038  6.028329
28       japon            8        1749  6.167139
29      italia            6        1512  7.053824
30   marruecos            4        1236  7.084986
31       india            8        2381  5.419263
32          uk            4         687  4.988669
33    singapur            7        2032  8.050992
34      suecia            7        1959  4.005666
35     noruega            5        1046  5.747875
36    portugal            6        1151  5.441926
37     ecuador            5         798  5.546742
38        peru            6         912  3.597734
39    burkinaf            3         671  2.220963
40    guayanaf            3         353  2.138810
41    mongolia            6        1194  2.614731
42    bulgaria            4        1203  3.943343
43        oman            3         578  2.178470

In [ ]:
# Convertir a minúsculas y eliminar espacios innecesarios (si es necesario)
df_merged['pais'] = df_merged['pais'].str.lower().str.strip()
counts['Country'] = counts['Country'].str.lower().str.strip()

# Filtrar las filas de df_merged donde 'pais' coincida con los valores de counts['Pais']
df_merged_33 = df_merged[df_merged['pais'].isin(counts['Country'])].reset_index(drop=True)

In [ ]:
df_merged_33

          pais  dimensiones  subespacio  salience
0       belice            5         806  2.322946
1   eslovaquia            4         857  3.461756
2     zimbabue            6        1670  2.133144
3      camboya            4        1248  2.543909
4        yemen            6        2122  2.991501
5       uzbeki            3         717  2.337110
6   luxemburgo            6        1401  4.297450
7      francia            7        1574  7.342776
8         eeuu            7        1241  8.662890
9        china            5         970  8.107649
10      mejico            7        2845  5.325779
11       rusia            6        1562  8.373938
12     espa√±a            6        1277  7.150142
13   argentina            4         922  5.192635
14    alemania            6        2243  7.648725
15       japon            8        1749  6.167139
16       india            8        2381  5.419263
17    singapur            7        2032  8.050992
18     noruega            5        1046  5.747875
19    portugal            6        1151  5.441926
20        peru            6         912  3.597734
21    burkinaf            3         671  2.220963
22    bulgaria            4        1203  3.943343

In [ ]:
import pandas as pd
pd.reset_option('display.float_format')
print(df_merged_33['salience'].head())

0    2.322946
1    3.461756
2    2.133144
3    2.543909
4    2.991501
Name: salience, dtype: float64

In [ ]:
df_merged_33['salience'] = df_merged_33['salience'].round(2)
df_merged_33

          pais  dimensiones  subespacio  salience
0       belice            5         806      2.32
1   eslovaquia            4         857      3.46
2     zimbabue            6        1670      2.13
3      camboya            4        1248      2.54
4        yemen            6        2122      2.99
5       uzbeki            3         717      2.34
6   luxemburgo            6        1401      4.30
7      francia            7        1574      7.34
8         eeuu            7        1241      8.66
9        china            5         970      8.11
10      mejico            7        2845      5.33
11       rusia            6        1562      8.37
12     espa√±a            6        1277      7.15
13   argentina            4         922      5.19
14    alemania            6        2243      7.65
15       japon            8        1749      6.17
16       india            8        2381      5.42
17    singapur            7        2032      8.05
18     noruega            5        1046      5.75
19    portugal            6        1151      5.44
20        peru            6         912      3.60
21    burkinaf            3         671      2.22
22    bulgaria            4        1203      3.94

In [ ]:
df_merged_33 = df_merged_33.rename(columns={
    'pais': 'country',
    'dimensiones': 'dimensions',
    'subespacio': 'subspace',
    'salience': 'salience'
})
df_merged_33

       country  dimensions  subspace  salience
0       belice           5       806      2.32
1   eslovaquia           4       857      3.46
2     zimbabue           6      1670      2.13
3      camboya           4      1248      2.54
4        yemen           6      2122      2.99
5       uzbeki           3       717      2.34
6   luxemburgo           6      1401      4.30
7      francia           7      1574      7.34
8         eeuu           7      1241      8.66
9        china           5       970      8.11
10      mejico           7      2845      5.33
11       rusia           6      1562      8.37
12     espa√±a           6      1277      7.15
13   argentina           4       922      5.19
14    alemania           6      2243      7.65
15       japon           8      1749      6.17
16       india           8      2381      5.42
17    singapur           7      2032      8.05
18     noruega           5      1046      5.75
19    portugal           6      1151      5.44
20        peru           6       912      3.60
21    burkinaf           3       671      2.22
22    bulgaria           4      1203      3.94

In [ ]:
import pandas as pd

corr_value = df_merged_33[['dimensions', 'salience']].corr(method='pearson')
print(corr_value)

            dimensions  salience
dimensions    1.000000  0.550974
salience      0.550974  1.000000

In [ ]:
corr_spearman = df_merged_33[['dimensions', 'salience']].corr(method='spearman')
print(corr_spearman)

            dimensions  salience
dimensions    1.000000  0.547192
salience      0.547192  1.000000

In [ ]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr


# Calculamos la correlación de Pearson (para relación lineal)
pearson_corr, pearson_p = pearsonr(df_merged_33["dimensions"], df_merged_33["salience"])

# Calculamos la correlación de Spearman (para rangos)
spearman_corr, spearman_p = spearmanr(df_merged_33["dimensions"], df_merged_33["salience"])

print(f"Pearson: r = {pearson_corr:.3f}, p = {pearson_p:.3e}")
print(f"Spearman: r = {spearman_corr:.3f}, p = {spearman_p:.3e}")

Pearson: r = 0.551, p = 6.435e-03
Spearman: r = 0.547, p = 6.887e-03

In [ ]:
df_merged_33 = df_merged_33.rename(columns={
    'country': 'Country',
    'dimensions': 'Dimensions',
    'subspace': 'Subspace',
    'salience': 'Salience'
})
df_merged_33

       Country  Dimensions  Subspace  Salience
0       belice           5       806      2.32
1   eslovaquia           4       857      3.46
2     zimbabue           6      1670      2.13
3      camboya           4      1248      2.54
4        yemen           6      2122      2.99
5       uzbeki           3       717      2.34
6   luxemburgo           6      1401      4.30
7      francia           7      1574      7.34
8         eeuu           7      1241      8.66
9        china           5       970      8.11
10      mejico           7      2845      5.33
11       rusia           6      1562      8.37
12     espa√±a           6      1277      7.15
13   argentina           4       922      5.19
14    alemania           6      2243      7.65
15       japon           8      1749      6.17
16       india           8      2381      5.42
17    singapur           7      2032      8.05
18     noruega           5      1046      5.75
19    portugal           6      1151      5.44
20        peru           6       912      3.60
21    burkinaf           3       671      2.22
22    bulgaria           4      1203      3.94

In [ ]:
df_styled = df_merged_33.style.format({
    "salience": "{:.2f}",
    "dimensions": "{:.0f}"  # Asumiendo que las dimensiones son números enteros
}).set_properties(**{'text-align': 'center'}) \
  .set_table_styles([{
      'selector': 'th',
      'props': [('text-align', 'center')]
  }]) \
  .set_caption("Table 6. Prototypes: Highest Salience, Dimensions, Subspaces and Salience (Likert Scale)")

# Mostrar la tabla estilizada
df_styled